name = "a0b_stm32f401_gpio"
description = "A0B: STM32F401 GPIO/EXTI"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "stm32", "stm32f401", "gpio", "exti"]

project-files = ["gnat/a0b_stm32f401_gpio.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_exti = "*"
a0b_gpio = "*"
a0b_stm32f401 = "*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]
